### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by hoanggianguet** [tahaipek/Angular-2-Github-Search-Profile#2]
I want to deploy app to server. I want to know how you deploy app to github.io. I do so it not working.

**Comment by katsos** [comment]
@hoanggianguet 
Check this branch https://github.com/tahaipek/Angular-2-Github-Search-Profile/tree/gh-pages.
Every Github project which has a gh-pages branch can be accessed through github.io as a web page.
Check this too https://pages.github.com/

**Comment by tahaipek** [comment]
Thanks for answer @katsos
