### ISSUE TITLE
my-app selector error

### ISSUE THREAD

**Issue by YogeshSonar** [tahaipek/Angular-2-Github-Search-Profile#3]
Hi sir,
I have seen your github profile search project. It really nice working and UI interface.
I download source code from **tahaipek/Angular-2-Github-Search-Profile** im trying to run this but it give error in console panel .

Plz fix this ASAP.

**Comment by tahaipek** [comment]
Hello @YogeshSonar 
Check this commit 6b35624152f7e7949b4511a03a67e0a4676607f4
